### ISSUE TITLE
clevertap-web-sdk not working with Angular-SSR build

### ISSUE THREAD

**Issue by 7abhik** [CleverTap/clevertap-web-sdk#102] opened 2022-12-20 13:15 UTC
Getting window is not define,while creating angular SSR build
![image](https://user-images.githubusercontent.com/28747452/208675832-499f9cc7-b5b1-4e97-9793-ce701dcf4dee.png)

**Comment by akashvercetti** [comment] 2022-12-26 14:49
Hi @7abhik , our SDK is a typically a client side only library and does not by its nature support SSR.
Having said that, there might be a workaround here as a user has suggested: https://github.com/CleverTap/clevertap-web-sdk/issues/39

**Comment by KambleSonam** [comment] 2023-07-12 11:29
Closing this issue. Kindly reopen the ticket if the issue isn't solved.

**Closed** 2023-07-12 11:30 UTC
